require File.expand_path(File.dirname(__FILE__) + '/../lib/mover/gems')
Mover::Gems.activate(:active_wrapper)

require 'active_wrapper/tasks'

ActiveWrapper::Tasks.new(
  :base => File.dirname(__FILE__),
  :env => ENV['ENV']
)