require File.expand_path(File.dirname(__FILE__) + '/../lib/mover/gems')
Mover::Gems.require(:spec_rake)

require 'active_wrapper/tasks'

ActiveWrapper::Tasks.new(
  :base => File.dirname(__FILE__),
  :env => ENV['ENV']
)